### ISSUE TITLE
AzureMapPopup 'options' prop

### ISSUE THREAD

**Issue by orlahowell** [WiredSolutions/react-azure-maps#36]
Currently working on a project needing a lot of markers, each with a popup on hover. I was planning to implement something like this: [reusing a popup with multiple points](https://docs.microsoft.com/en-us/azure/azure-maps/map-add-popup#reusing-a-popup-with-multiple-points)

I'm trying to alter the position with state, but after the initial load nothing within the options prop changes. I think it's due to the use of memo in AzureMapPopup.tsx, though I'm not exactly sure of the changes that need to be made to make it work.

If you think there's a better way to do this or could give me an example of implementation that'd be really useful!

**Comment by msasinowski** [comment]
You are right, props change for `AzureMapPopup ` don't have any effect, we handle this case inside custom hook `useCreatePopup` so after any changes that will be made in options or content, the popup ref will re-render correctly. 

Thanks for reporting the issue, we try to resolve this in next version, probably tomorrow we will push a new version with some minor fixes including this.

**Comment by srednicki95** [comment]
@orlahowell Thanks for your feedback. We will implement that example in Playgroud.

**Comment by srednicki95** [comment]
@orlahowell We just added effect for popup options in version 0.0.4. Also we implemented example just like your example  but with mouse-enter(hover) event on marker instead of click: [https://github.com/WiredSolutions/react-azure-maps-playground/blob/master/src/examples/MultiplePointWithPopup.tsx](url)

Thanks again for your feedback, feel free to create next if you have any problems.

**Comment by orlahowell** [comment]
Really appreciate it! Have managed to implement your example - really helpful!
